[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# هذا يحل مشكلة الروابط الداخلية في تطبيقات SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
